# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guidlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_guid', models.CharField(max_length=40)),
                ('gl_gt_gameId', models.IntegerField()),
                ('gl_insertDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('gl_exportDate', models.DateTimeField(blank=True, null=True)),
                ('gl_bannedDate', models.DateTimeField(blank=True, null=True)),
                ('gl_unbannedDate', models.DateTimeField(blank=True, null=True)),
                ('gl_currentBanStatus', models.IntegerField()),
                ('gl_desc', models.TextField()),
                ('gl_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
